services:
  picomp-chess-demo:
    image: ${OCIR_REGISTRY}/picomp-chess-demo:latest
    container_name: picomp-chess-demo
    restart: unless-stopped
    environment:
      - VITE_PICO_API_KEY=${VITE_PICO_API_KEY}
    networks:
      - proxy-nw

networks:
  proxy-nw:
    external: true
