server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # SPA 라우팅 대응 (모든 경로를 index.html로 유도)
        try_files $uri $uri/ /index.html;
    }

    # 에러 핸들링
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
